#!/usr/bin/env python3
"""Print a compact KPI report from artifacts generated by the Portfolio Lab.
Run:
    python print_report.py artifacts/risk_report.json artifacts/risk_report_mc.json
The second file is optional.
"""
import sys, json, os

def pct(x):
    return f"{x*100:.2f}%"

def load_json(path):
    if not path or not os.path.exists(path):
        return None
    with open(path, 'r') as f:
        return json.load(f)

def main():
    risk_path = sys.argv[1] if len(sys.argv) > 1 else 'artifacts/risk_report.json'
    mc_path   = sys.argv[2] if len(sys.argv) > 2 else 'artifacts/risk_report_mc.json'

    rpt = load_json(risk_path)
    mc  = load_json(mc_path)

    if not rpt:
        print('risk_report.json not found. Export artifacts from the app first.')
        raise SystemExit(1)

    print('\n=== Portfolio Lab Report ===\n')
    print(f"Universe: {len(rpt.get('tickers', []))} assets  | shrinkage: {rpt.get('use_shrink', True)}  | shorting: {rpt.get('allow_short', False)}")
    print(f"Risk-free (annual): {rpt.get('rf', 0.02):.2%}\n")

    t = rpt['tangency']; m = rpt['minvar']
    print('Tangency:  ret', pct(t['ret']), '  vol', pct(t['vol']), '  Sharpe', f"{t['sharpe']:.2f}")
    print('Min-Var:   ret', pct(m['ret']), '  vol', pct(m['vol']), '  Sharpe', f"{m['sharpe']:.2f}")

    if mc and 'tangency' in mc:
        tg = mc['tangency']
        print('\nMonte Carlo (Tangency, 95%):')
        print('  VaR_1d ', pct(abs(tg['VaR_95_1d'])), ' | CVaR_1d ', pct(abs(tg['CVaR_95_1d'])))
        print('  VaR_21d', pct(abs(tg['VaR_95_21d'])), ' | CVaR_21d', pct(abs(tg['CVaR_95_21d'])))
        print('  Drawdowns (sim): median', pct(abs(tg['DD_median_sim'])), ', worst', pct(abs(tg['DD_min_sim'])))

    print('\nDone.')

if __name__ == '__main__':
    main()
